force-app/main/default/objects/Flow_Test__c/Flow_Test__c.object-meta.xml
<CustomObject>
    <label>Flow Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flow Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flow_Test__c/fields/Flow_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Name__c</fullName>
    <externalId>true</externalId>
    <label>Flow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_Test_Result__c/Flow_Test_Result__c.object-meta.xml
<CustomObject>
    <label>Flow Test Result</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flow Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flow_Test_Result__c/fields/Execution_Duration_ms__c.field-meta.xml
<CustomField>
    <fullName>Execution_Duration_ms__c</fullName>
    <inlineHelpText>Optional timing info</inlineHelpText>
    <label>Execution Duration (ms)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flow_Test_Result__c/fields/Flow_Test__c.field-meta.xml
<CustomField>
    <fullName>Flow_Test__c</fullName>
    <label>Flow Test</label>
    <referenceTo>Flow_Test__c</referenceTo>
    <relationshipLabel>Flow Tests</relationshipLabel>
    <relationshipName>Flow_Test_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Flow_Test_Result__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <inlineHelpText>Execution summary / errors</inlineHelpText>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Flow_Test_Result__c/fields/Run_By__c.field-meta.xml
<CustomField>
    <fullName>Run_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who executed the test</inlineHelpText>
    <label>Run By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Ran_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flow_Test_Result__c/fields/Run_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Run_Date_Time__c</fullName>
    <inlineHelpText>When test executed</inlineHelpText>
    <label>Run Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flow_Test_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FG_FlowTestRunner.cls
public with sharing class FG_FlowTestRunner {
    
    @AuraEnabled
    public static Flow_Test_Result__c runFlowTest(String flowApiName){
        Flow_Test_Result__c result = new Flow_Test_Result__c();
        try {
            Datetime startTime = System.now();

            // Run The flow
            Flow.Interview interview = Flow.Interview.CreateInterview(flowApiName, new Map<String, Object>());
            interview.start();
            
            // Calc Execution Duration
            Long exe_duration = System.now().getTime() - startTime.getTime();

            // Prepare result record
            result.Status__c = 'Passed';
            result.Log_Details__c = 'Flow Executed Successfully: ' + flowApiName;
            result.Execution_Duration_ms__c = exe_duration;

        } catch (Exception e) {
            result.Status__c = 'Failed';
            result.Log_Details__c = 'Flow Execution Failed: ' + e.getMessage();
        }

        result.Run_Date_Time__c = System.now();

        //Associate with Flow_Test__c
        Flow_Test__c parent_test = [SELECT Id FROM Flow_Test__c Where Flow_Name__c =:flowApiName LIMIT 1];
        result.Flow_Test__c = parent_test.Id;
        result.Run_By__c = UserInfo.getUserId();

        insert result;
        return result;
    }

}